export const LOGIN = "LOGIN"
export const REGISTER = "REGISTER"
export const LOAD_USER = "LOAD_USER"
export const AUTH_ERROR = "AUTH_ERROR"
export const SET_ALERT = "SET_ALERT"
export const REMOVE_ALERT = "REMOVE_ALERT"
export const FADE_OUT = "FADE_OUT"